/**
 * Binding types are generated by `wrangler types`. This overlay contains only
 * secrets and the one deployment-time optional variable Wrangler cannot infer
 * from the checked-in sample configuration.
 */
export type Env = Omit<CloudflareBindings, "PUBLIC_BASE_URL"> & {
  PUBLIC_BASE_URL?: string;
  SHARING_INTERNAL_SECRET?: string;
  BOOTSTRAP_LINK_SECRET?: string;
  BOOTSTRAP_LINK_SECRET_KEY_ID?: string;
  BOOTSTRAP_LINK_SECRET_PREVIOUS?: string;
  BOOTSTRAP_LINK_SECRET_PREVIOUS_KEY_ID?: string;
  DEVICE_RUNTIME_SECRET?: string;
  DEVICE_RUNTIME_SECRET_KEY_ID?: string;
  DEVICE_RUNTIME_SECRET_PREVIOUS?: string;
  DEVICE_RUNTIME_SECRET_PREVIOUS_KEY_ID?: string;
  AUTH_ROTATION_GRACE_UNTIL_MS?: string;
};
