// Generated from contracts/error-codes.json.
pub const APP_ERROR_CODES: &[&str] = &[
    "invalid_input",
    "invalid_state",
    "unsupported",
    "temporary_failure",
    "temporary_unavailable",
    "network_unavailable",
    "request_timeout",
    "restore_failed",
    "storage_integrity_error",
    "not_found",
    "conflict",
    "rate_limited",
    "request_too_large",
    "payload_too_large",
    "invalid_capability",
    "capability_expired",
    "runtime_auth_expired",
    "runtime_auth_invalid",
    "runtime_misconfigured",
    "cloudflare_permission_denied",
    "cloudflare_storage_setup_failed",
    "cloudflare_worker_deploy_failed",
    "cloudflare_runtime_not_ready",
    "cloudflare_setup_incomplete",
    "runtime_mismatch",
    "runtime_missing_group_outbox",
    "enrollment_required",
    "device_revoked",
    "upgrade_required",
    "keypackage_expired",
    "keypackage_lifetime_invalid",
    "keypackage_refresh_pending",
    "keypackage_publish_failed",
    "pool_empty",
    "device_clock_invalid",
    "identity_bundle_conflict",
    "identity_refresh_required",
    "contact_share_offline",
    "contact_share_publish_failed",
    "contact_share_rotation_unverified",
    "contact_share_revoked",
    "relationship_closed",
    "group_transition_conflict",
    "roster_version_conflict",
    "already_sealed",
    "challenge_replayed",
    "group_authorization_conflict",
    "group_authorization_uninitialized",
    "group_join_claimed",
    "group_join_lease_invalid",
    "group_join_terminal",
    "group_leave_claimed",
    "group_leave_lease_invalid",
    "group_leave_terminal",
    "group_membership_revoked",
    "group_membership_uninitialized",
    "group_sealed",
    "group_transition_invalid",
    "group_transition_required",
    "invalid_ack",
    "invalid_invite",
    "message_request_capacity_exceeded",
    "range_not_satisfiable",
    "unsupported_version",
    "blob_not_found",
    "profile_required",
    "profile_locked",
    "profile_passphrase_required",
    "auth_failed",
    "unexpected_error",
];

const APP_ERROR_DEFAULTS: &[(&str, &str, bool, Option<&str>)] = &[
    ("invalid_input", "validation", false, None),
    ("invalid_state", "core", false, Some("restart_app")),
    ("unsupported", "core", false, Some("upgrade_app")),
    ("temporary_failure", "transport", true, Some("retry")),
    ("temporary_unavailable", "transport", true, Some("retry")),
    ("network_unavailable", "transport", true, Some("reconnect")),
    ("request_timeout", "transport", true, Some("retry")),
    ("restore_failed", "storage", false, Some("copy_diagnostics")),
    (
        "storage_integrity_error",
        "storage",
        false,
        Some("copy_diagnostics"),
    ),
    ("not_found", "transport", false, None),
    ("conflict", "transport", true, Some("sync_now")),
    ("rate_limited", "transport", true, Some("retry_later")),
    ("request_too_large", "validation", false, None),
    ("payload_too_large", "validation", false, None),
    (
        "invalid_capability",
        "security",
        false,
        Some("refresh_identity"),
    ),
    (
        "capability_expired",
        "security",
        true,
        Some("refresh_identity"),
    ),
    (
        "runtime_auth_expired",
        "runtime",
        true,
        Some("reconnect_runtime"),
    ),
    (
        "runtime_auth_invalid",
        "runtime",
        false,
        Some("reconnect_runtime"),
    ),
    (
        "runtime_misconfigured",
        "runtime",
        false,
        Some("upgrade_runtime"),
    ),
    (
        "cloudflare_permission_denied",
        "runtime",
        false,
        Some("retry"),
    ),
    (
        "cloudflare_storage_setup_failed",
        "runtime",
        true,
        Some("retry"),
    ),
    (
        "cloudflare_worker_deploy_failed",
        "runtime",
        true,
        Some("retry"),
    ),
    (
        "cloudflare_runtime_not_ready",
        "runtime",
        true,
        Some("retry"),
    ),
    (
        "cloudflare_setup_incomplete",
        "runtime",
        true,
        Some("retry"),
    ),
    (
        "runtime_mismatch",
        "runtime",
        false,
        Some("reconnect_runtime"),
    ),
    (
        "runtime_missing_group_outbox",
        "runtime",
        false,
        Some("upgrade_runtime"),
    ),
    (
        "enrollment_required",
        "runtime",
        false,
        Some("reconnect_runtime"),
    ),
    ("device_revoked", "security", false, None),
    (
        "upgrade_required",
        "runtime",
        false,
        Some("upgrade_runtime"),
    ),
    ("keypackage_expired", "mls", true, Some("refresh_identity")),
    (
        "keypackage_lifetime_invalid",
        "mls",
        false,
        Some("refresh_identity"),
    ),
    ("keypackage_refresh_pending", "mls", true, Some("reconnect")),
    ("keypackage_publish_failed", "mls", true, Some("retry")),
    ("pool_empty", "mls", true, None),
    ("device_clock_invalid", "security", false, None),
    (
        "identity_bundle_conflict",
        "identity",
        true,
        Some("sync_now"),
    ),
    (
        "identity_refresh_required",
        "identity",
        true,
        Some("refresh_identity"),
    ),
    ("contact_share_offline", "identity", true, Some("reconnect")),
    (
        "contact_share_publish_failed",
        "identity",
        true,
        Some("retry"),
    ),
    (
        "contact_share_rotation_unverified",
        "identity",
        true,
        Some("reconnect"),
    ),
    ("contact_share_revoked", "identity", false, None),
    ("relationship_closed", "identity", false, None),
    ("group_transition_conflict", "group", true, Some("sync_now")),
    ("roster_version_conflict", "group", true, Some("sync_now")),
    ("already_sealed", "group", false, None),
    (
        "challenge_replayed",
        "security",
        false,
        Some("reconnect_runtime"),
    ),
    (
        "group_authorization_conflict",
        "group",
        true,
        Some("sync_now"),
    ),
    (
        "group_authorization_uninitialized",
        "group",
        true,
        Some("sync_now"),
    ),
    ("group_join_claimed", "group", true, Some("retry_later")),
    ("group_join_lease_invalid", "group", true, Some("retry")),
    ("group_join_terminal", "group", false, None),
    ("group_leave_claimed", "group", true, Some("retry_later")),
    ("group_leave_lease_invalid", "group", true, Some("retry")),
    ("group_leave_terminal", "group", false, None),
    ("group_membership_revoked", "group", false, None),
    (
        "group_membership_uninitialized",
        "group",
        true,
        Some("sync_now"),
    ),
    ("group_sealed", "group", false, None),
    ("group_transition_invalid", "group", false, Some("sync_now")),
    ("group_transition_required", "group", true, Some("sync_now")),
    ("invalid_ack", "validation", false, Some("sync_now")),
    ("invalid_invite", "validation", false, None),
    (
        "message_request_capacity_exceeded",
        "transport",
        true,
        Some("retry_later"),
    ),
    ("range_not_satisfiable", "validation", false, None),
    (
        "unsupported_version",
        "runtime",
        false,
        Some("upgrade_runtime"),
    ),
    ("blob_not_found", "storage", false, None),
    ("profile_required", "core", false, None),
    ("profile_locked", "security", false, Some("retry")),
    (
        "profile_passphrase_required",
        "security",
        false,
        Some("retry"),
    ),
    ("auth_failed", "security", false, Some("retry")),
    ("unexpected_error", "core", true, Some("retry")),
];

pub fn is_registered_app_error(code: &str) -> bool {
    APP_ERROR_CODES.contains(&code)
}

pub fn is_allowed_error_arg(code: &str, arg: &str) -> bool {
    match (code, arg) {
        _ => false,
    }
}

pub fn app_error_defaults(
    code: &str,
) -> Option<(
    crate::error::ErrorDomain,
    bool,
    Option<crate::error::RecoveryAction>,
)> {
    use crate::error::{ErrorDomain::*, RecoveryAction::*};
    let (_, domain, retryable, action) = APP_ERROR_DEFAULTS
        .iter()
        .find(|(candidate, _, _, _)| *candidate == code)?;
    let domain = match *domain {
        "core" => Core,
        "validation" => Validation,
        "identity" => Identity,
        "mls" => Mls,
        "transport" => Transport,
        "runtime" => Runtime,
        "storage" => Storage,
        "security" => Security,
        "group" => Group,
        _ => return None,
    };
    let action = match *action {
        None => None,
        Some("retry") => Some(Retry),
        Some("retry_later") => Some(RetryLater),
        Some("sync_now") => Some(SyncNow),
        Some("refresh_identity") => Some(RefreshIdentity),
        Some("reconnect") => Some(Reconnect),
        Some("reconnect_runtime") => Some(ReconnectRuntime),
        Some("upgrade_app") => Some(UpgradeApp),
        Some("upgrade_runtime") => Some(UpgradeRuntime),
        Some("restart_app") => Some(RestartApp),
        Some("copy_diagnostics") => Some(CopyDiagnostics),
        Some(_) => return None,
    };
    Some((domain, *retryable, action))
}
