// Generated from contracts/error-codes.json. Do not add user-facing copy elsewhere.
export const ERROR_CATALOG = {
  invalid_input: ["Invalid input", "Check the information you entered and try again.", false, null],
  invalid_state: ["TapChat is not ready", "Restart TapChat and try again.", false, "restart_app"],
  unsupported: ["Unsupported operation", "Update TapChat to continue.", false, "upgrade_app"],
  temporary_failure: ["Temporary problem", "Try again in a moment.", true, "retry"],
  temporary_unavailable: ["Service unavailable", "The TapChat service is temporarily unavailable. Try again shortly.", true, "retry"],
  network_unavailable: ["You're offline", "Check your connection and try again.", true, "reconnect"],
  request_timeout: ["Request timed out", "The service did not respond in time. Try again.", true, "retry"],
  restore_failed: ["Profile could not be restored", "TapChat could not restore this profile.", false, "copy_diagnostics"],
  storage_integrity_error: ["Storage problem", "TapChat detected inconsistent stored data.", false, "copy_diagnostics"],
  not_found: ["Not found", "The requested item is no longer available.", false, null],
  conflict: ["Changes conflict", "Sync the latest changes and try again.", true, "sync_now"],
  rate_limited: ["Too many requests", "Wait a moment before trying again.", true, "retry_later"],
  request_too_large: ["Request too large", "Reduce the request size and try again.", false, null],
  payload_too_large: ["Message too large", "Reduce the message or attachment size and try again.", false, null],
  invalid_capability: ["Authorization is no longer valid", "Refresh the contact or runtime authorization and try again.", false, "refresh_identity"],
  capability_expired: ["Authorization expired", "Refresh the contact information and try again.", true, "refresh_identity"],
  runtime_auth_expired: ["Runtime authorization expired", "Reconnect to your TapChat service and try again.", true, "reconnect_runtime"],
  runtime_auth_invalid: ["Runtime authorization failed", "Reconnect this device to your TapChat service.", false, "reconnect_runtime"],
  runtime_misconfigured: ["Runtime configuration problem", "Update or redeploy your Cloudflare runtime.", false, "upgrade_runtime"],
  cloudflare_permission_denied: ["Cloudflare permission required", "Reconnect Cloudflare and allow TapChat to manage Workers and R2 storage.", false, "retry"],
  cloudflare_storage_setup_failed: ["Cloudflare storage setup failed", "TapChat could not prepare its Cloudflare R2 storage. Try again.", true, "retry"],
  cloudflare_worker_deploy_failed: ["Cloudflare Worker deployment failed", "TapChat could not deploy its Cloudflare Worker. Try again.", true, "retry"],
  cloudflare_runtime_not_ready: ["Cloudflare runtime is not ready", "The Worker was deployed but did not become ready. Try deployment again.", true, "retry"],
  cloudflare_setup_incomplete: ["Cloudflare setup incomplete", "The Worker may already be deployed, but this device did not finish setup. Retry to resume.", true, "retry"],
  runtime_mismatch: ["Wrong runtime", "This device is connected to a different TapChat runtime.", false, "reconnect_runtime"],
  runtime_missing_group_outbox: ["Runtime upgrade required", "Upgrade your Cloudflare runtime before creating a group.", false, "upgrade_runtime"],
  enrollment_required: ["Device enrollment required", "Enroll this device with your TapChat runtime.", false, "reconnect_runtime"],
  device_revoked: ["Device revoked", "This device no longer has access to the TapChat runtime.", false, null],
  upgrade_required: ["Update required", "Update TapChat and your Cloudflare runtime to continue.", false, "upgrade_runtime"],
  keypackage_expired: ["Secure contact information expired", "This contact needs to open TapChat before a secure conversation can be started.", true, "refresh_identity"],
  keypackage_lifetime_invalid: ["Invalid secure contact information", "Refresh this contact's secure information and try again.", false, "refresh_identity"],
  keypackage_refresh_pending: ["Refreshing secure contact information", "TapChat is refreshing your secure contact information. Existing conversations still work.", true, "reconnect"],
  keypackage_publish_failed: ["Secure contact update failed", "TapChat could not publish refreshed secure contact information.", true, "retry"],
  device_clock_invalid: ["Incorrect device time", "Your device date and time appear to be incorrect. Correct them and try again.", false, null],
  identity_bundle_conflict: ["Identity changed on another device", "TapChat will sync the latest identity information before retrying.", true, "sync_now"],
  identity_refresh_required: ["Contact refresh required", "Refresh this contact before continuing.", true, "refresh_identity"],
  contact_share_offline: ["Connect before rotating", "Connect to your TapChat service before rotating the share link.", true, "reconnect"],
  contact_share_publish_failed: ["Share link was not rotated", "TapChat could not publish the new share link. Try again.", true, "retry"],
  contact_share_rotation_unverified: ["Share link status is unknown", "TapChat couldn't verify whether the link was rotated. Reconnect to check which link is active.", true, "reconnect"],
  contact_share_revoked: ["Share link expired", "This share link is no longer valid. Ask the contact for a new link.", false, null],
  relationship_closed: ["Conversation unavailable", "This contact relationship is closed.", false, null],
  group_transition_conflict: ["Group changed", "Sync the latest group state and try again.", true, "sync_now"],
  roster_version_conflict: ["Group membership changed", "Sync the latest group membership and try again.", true, "sync_now"],
  already_sealed: ["Group already closed", "This group is already closed.", false, null],
  challenge_replayed: ["Authorization challenge expired", "Reconnect this device to your TapChat service.", false, "reconnect_runtime"],
  group_authorization_conflict: ["Group authorization changed", "Sync the latest group state and try again.", true, "sync_now"],
  group_authorization_uninitialized: ["Group is not ready", "Sync the group before trying again.", true, "sync_now"],
  group_join_claimed: ["Join request is being processed", "Wait a moment and try again.", true, "retry_later"],
  group_join_lease_invalid: ["Join approval expired", "Retry the group join approval.", true, "retry"],
  group_join_terminal: ["Join request completed", "This join request can no longer be changed.", false, null],
  group_leave_claimed: ["Leave request is being processed", "Wait a moment and try again.", true, "retry_later"],
  group_leave_lease_invalid: ["Leave approval expired", "Retry the group leave operation.", true, "retry"],
  group_leave_terminal: ["Leave request completed", "This leave request can no longer be changed.", false, null],
  group_membership_revoked: ["Group access removed", "You no longer have access to this group.", false, null],
  group_membership_uninitialized: ["Group membership is not ready", "Sync the group membership and try again.", true, "sync_now"],
  group_sealed: ["Group closed", "No more messages can be sent to this group.", false, null],
  group_transition_invalid: ["Invalid group update", "Sync the latest group state before continuing.", false, "sync_now"],
  group_transition_required: ["Group update required", "Sync the latest group state before continuing.", true, "sync_now"],
  invalid_ack: ["Invalid sync acknowledgement", "Sync again before acknowledging messages.", false, "sync_now"],
  invalid_invite: ["Invalid invite", "Ask for a new group invite link.", false, null],
  message_request_capacity_exceeded: ["Too many message requests", "Wait before sending another message request.", true, "retry_later"],
  range_not_satisfiable: ["Attachment range unavailable", "Retry the attachment download.", false, null],
  unsupported_version: ["Protocol update required", "Update TapChat and your Cloudflare runtime to continue.", false, "upgrade_runtime"],
  blob_not_found: ["Attachment unavailable", "This attachment is no longer available.", false, null],
  profile_required: ["Profile required", "Create or select a profile before continuing.", false, null],
  profile_locked: ["Profile locked", "Unlock this profile to continue.", false, "retry"],
  profile_passphrase_required: ["Passphrase required", "Enter the profile passphrase to continue.", false, "retry"],
  auth_failed: ["Authentication failed", "The profile passphrase is incorrect. Try again.", false, "retry"],
  unexpected_error: ["Something went wrong", "Something went wrong. Try again.", true, "retry"],
} as const;

export const ERROR_DEFAULTS = {
  invalid_input: ["validation", false, null],
  invalid_state: ["core", false, "restart_app"],
  unsupported: ["core", false, "upgrade_app"],
  temporary_failure: ["transport", true, "retry"],
  temporary_unavailable: ["transport", true, "retry"],
  network_unavailable: ["transport", true, "reconnect"],
  request_timeout: ["transport", true, "retry"],
  restore_failed: ["storage", false, "copy_diagnostics"],
  storage_integrity_error: ["storage", false, "copy_diagnostics"],
  not_found: ["transport", false, null],
  conflict: ["transport", true, "sync_now"],
  rate_limited: ["transport", true, "retry_later"],
  request_too_large: ["validation", false, null],
  payload_too_large: ["validation", false, null],
  invalid_capability: ["security", false, "refresh_identity"],
  capability_expired: ["security", true, "refresh_identity"],
  runtime_auth_expired: ["runtime", true, "reconnect_runtime"],
  runtime_auth_invalid: ["runtime", false, "reconnect_runtime"],
  runtime_misconfigured: ["runtime", false, "upgrade_runtime"],
  cloudflare_permission_denied: ["runtime", false, "retry"],
  cloudflare_storage_setup_failed: ["runtime", true, "retry"],
  cloudflare_worker_deploy_failed: ["runtime", true, "retry"],
  cloudflare_runtime_not_ready: ["runtime", true, "retry"],
  cloudflare_setup_incomplete: ["runtime", true, "retry"],
  runtime_mismatch: ["runtime", false, "reconnect_runtime"],
  runtime_missing_group_outbox: ["runtime", false, "upgrade_runtime"],
  enrollment_required: ["runtime", false, "reconnect_runtime"],
  device_revoked: ["security", false, null],
  upgrade_required: ["runtime", false, "upgrade_runtime"],
  keypackage_expired: ["mls", true, "refresh_identity"],
  keypackage_lifetime_invalid: ["mls", false, "refresh_identity"],
  keypackage_refresh_pending: ["mls", true, "reconnect"],
  keypackage_publish_failed: ["mls", true, "retry"],
  device_clock_invalid: ["security", false, null],
  identity_bundle_conflict: ["identity", true, "sync_now"],
  identity_refresh_required: ["identity", true, "refresh_identity"],
  contact_share_offline: ["identity", true, "reconnect"],
  contact_share_publish_failed: ["identity", true, "retry"],
  contact_share_rotation_unverified: ["identity", true, "reconnect"],
  contact_share_revoked: ["identity", false, null],
  relationship_closed: ["identity", false, null],
  group_transition_conflict: ["group", true, "sync_now"],
  roster_version_conflict: ["group", true, "sync_now"],
  already_sealed: ["group", false, null],
  challenge_replayed: ["security", false, "reconnect_runtime"],
  group_authorization_conflict: ["group", true, "sync_now"],
  group_authorization_uninitialized: ["group", true, "sync_now"],
  group_join_claimed: ["group", true, "retry_later"],
  group_join_lease_invalid: ["group", true, "retry"],
  group_join_terminal: ["group", false, null],
  group_leave_claimed: ["group", true, "retry_later"],
  group_leave_lease_invalid: ["group", true, "retry"],
  group_leave_terminal: ["group", false, null],
  group_membership_revoked: ["group", false, null],
  group_membership_uninitialized: ["group", true, "sync_now"],
  group_sealed: ["group", false, null],
  group_transition_invalid: ["group", false, "sync_now"],
  group_transition_required: ["group", true, "sync_now"],
  invalid_ack: ["validation", false, "sync_now"],
  invalid_invite: ["validation", false, null],
  message_request_capacity_exceeded: ["transport", true, "retry_later"],
  range_not_satisfiable: ["validation", false, null],
  unsupported_version: ["runtime", false, "upgrade_runtime"],
  blob_not_found: ["storage", false, null],
  profile_required: ["core", false, null],
  profile_locked: ["security", false, "retry"],
  profile_passphrase_required: ["security", false, "retry"],
  auth_failed: ["security", false, "retry"],
  unexpected_error: ["core", true, "retry"],
} as const;

export const ERROR_ALLOWED_ARGS: Partial<Record<keyof typeof ERROR_CATALOG, readonly string[]>> = {};

export type AppErrorCode = keyof typeof ERROR_CATALOG;
